### ISSUE TITLE
 'Unknown path components: /me/adaccounts'

### ISSUE THREAD

**Issue by rbaindourov** [facebook/facebook-php-ads-sdk#152]
I'm following along with this [QuickStart](https://developers.facebook.com/docs/marketing-api/quickstart). Which honestly makes huge assumptions, and needs to be clearer. 

Because right now, I can't get past step 8.
I am getting this error.

```
<br />
<b>Fatal error</b>:  Uncaught exception 'FacebookAds\Http\Exception\AuthorizationException' with message 'Unknown path components: /me/adaccounts' in /Users/robert/dev/facebook-leads/vendor/facebook/php-ads-sdk/src/FacebookAds/Http/Exception/RequestException.php:137
Stack trace:
#0 /Users/robert/dev/facebook-leads/vendor/facebook/php-ads-sdk/src/FacebookAds/Http/Client.php(216): FacebookAds\Http\Exception\RequestException::create(Array, 400)
#1 /Users/robert/dev/facebook-leads/vendor/facebook/php-ads-sdk/src/FacebookAds/Http/Request.php(282): FacebookAds\Http\Client-&gt;sendRequest(Object(FacebookAds\Http\Request))
#2 /Users/robert/dev/facebook-leads/vendor/facebook/php-ads-sdk/src/FacebookAds/Api.php(152): FacebookAds\Http\Request-&gt;execute()
#3 /Users/robert/dev/facebook-leads/vendor/facebook/php-ads-sdk/src/FacebookAds/Api.php(194): FacebookAds\Api-&gt;executeRequest(Object(FacebookAds\Http\Request))
#4 /Users/robert/dev/facebook-leads/vendor/facebook/php-ads-sdk/src/FacebookAds/Object/AbstractCrudObject.php(373): FacebookAds\Api-&gt;ca in <b>/Users/robert/dev/facebook-leads/vendor/facebook/php-ads-sdk/src/FacebookAds/Http/Exception/RequestException.php</b> on line <b>137</b><br />
```

I've pasted the code around a bit in the quick start and here is what I came up with:

```php
<?php
require_once __DIR__ . '/vendor/autoload.php';

use Facebook\Facebook;
use Facebook\Exceptions\FacebookResponseException;
use Facebook\Exceptions\FacebookSDKException;
use FacebookAds\Api;
use FacebookAds\Object\AdUser;

// Init PHP Sessions
session_start();
date_default_timezone_set('America/Los_Angeles');
$conf = json_decode( file_get_contents('conf/conf.json'),  true  ) ;

$fb = new Facebook( $conf );

$helper = $fb->getRedirectLoginHelper();

if (!isset($_SESSION['facebook_access_token'])) {
  $_SESSION['facebook_access_token'] = null;
}

if (!$_SESSION['facebook_access_token']) {
  $helper = $fb->getRedirectLoginHelper();
  try {
    $_SESSION['facebook_access_token'] = (string) $helper->getAccessToken();
  } catch(FacebookResponseException $e) {
    // When Graph returns an error
    echo 'Graph returned an error: ' . $e->getMessage();
    exit;
  } catch(FacebookSDKException $e) {
    // When validation fails or other local issues
    echo 'Facebook SDK returned an error: ' . $e->getMessage();
    exit;
  }
}

if ($_SESSION['facebook_access_token']) {

  Api::init( $conf['app_id'], $conf['app_secret'], $_SESSION['facebook_access_token'] );
  $me = new AdUser('me');
  $my_adaccount = $me->getAdAccounts()->current();
  print_r($my_adaccount->getData());


} else {
  $permissions = ['ads_management'];
  $loginUrl = $helper->getLoginUrl('http://facebook.buildsavings.com/getAccessToken.php', $permissions );
  echo '<a href="' . $loginUrl . '">Log in with Facebook</a>';
}
```

So the above code is throwing that error, and the only thing that I can think of is that I have two ad accounts listed when I click on the "Get Ad Account" button on step 1 of the quick start. I'm on a Macbook Pro, with Apache 2.4, 

```sh
pro:~ robert$ php --version
PHP 5.5.27 (cli) (built: Jul 23 2015 00:21:59)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
```

That URI (facebook.buildsavings.com) is local by the way, I'm not doing anything on a public facing web server yet.

**Comment by pruno** [comment]
Hi @rbaindourov,

judging by the error message, it seems that 'me' can't be resolved, which might be an issue with the token. Can you please test your access_token in this tool? https://developers.facebook.com/tools/debug/

it should return your user id, app id and scopes ('ads_management')

**Comment by rbaindourov** [comment]
Access Token Info
App ID	319342228236164 : Advertising
User ID
1522519598067222 : Robert Baindourov
User last installed this app via API v2.x
Issued	1447180933 (49 minutes ago)
Expires	1452364933 (in about 2 months)
Valid	True
Origin	Web
Scopes	ads_management, public_profile

**Comment by pruno** [comment]
@rbaindourov,

please generate a curl equivalent of your requests.

change:

~~~php
Api::init($conf['app_id'], $conf['app_secret'], $_SESSION['facebook_access_token']);
~~~

with:

~~~php
use FacebookAds\Logger\CurlLogger;

Api::init($conf['app_id'], $conf['app_secret'], $_SESSION['facebook_access_token'])
  ->setLogger(new CurlLogger(fopen('<PATH_TO_FS>', 'w+')));
~~~

where <PATH_TO_FS> is a path that your webserver has writing permissions for.
all requests made with the SDK will be logged in their curl-equivalent form (feel free to obfuscate your access_token and appsecret_proof before posting here)

**Comment by rbaindourov** [comment]
I put it up on SSL'ed URL and it started working.
