### ISSUE TITLE
curl_setopt_array(): supplied argument is not a valid cURL handle resource (getting campaigns)

### ISSUE THREAD

**Issue by drum5ormore** [facebook/facebook-php-ads-sdk#207]
I recently upgraded my dev environment to PHP 5.5 and now I get the above error when calling getCampaigns() on FacebookAds\Object\AdAccount

Here's a stripped down version of the stack trace:

PHP Error[2]: curl_setopt_array(): supplied argument is not a valid cURL handle resource
    in file .../facebook/php-ads-sdk/src/FacebookAds/Http/Adapter/Curl/AbstractCurl.php at line 109
#0 .../facebook/php-ads-sdk/src/FacebookAds/Http/Adapter/Curl/AbstractCurl.php(109): curl_setopt_array()
#1 .../facebook/php-ads-sdk/src/FacebookAds/Http/Adapter/CurlAdapter.php(182): FacebookAds\Http\Adapter\Curl\Curl55->setoptArray()
#2 .../facebook/php-ads-sdk/src/FacebookAds/Http/Client.php(204): FacebookAds\Http\Adapter\CurlAdapter->sendRequest()
#3 .../facebook/php-ads-sdk/src/FacebookAds/Http/Request.php(282): FacebookAds\Http\Client->sendRequest()
#4 .../facebook/php-ads-sdk/src/FacebookAds/Api.php(152): FacebookAds\Http\Request->execute()
#5 .../facebook/php-ads-sdk/src/FacebookAds/Api.php(194): FacebookAds\Api->executeRequest()
#6 .../facebook/php-ads-sdk/src/FacebookAds/Object/AbstractCrudObject.php(373): FacebookAds\Api->call()
#7 .../facebook/php-ads-sdk/src/FacebookAds/Object/AbstractCrudObject.php(422): FacebookAds\Object\AdAccount->fetchConnection()
#8 .../facebook/php-ads-sdk/src/FacebookAds/Object/AdAccount.php(81): FacebookAds\Object\AdAccount->getManyByConnection()
#9 FacebookAds\Object\AdAccount->getCampaigns()

I tried applying the fix on this page, https://github.com/facebook/facebook-php-ads-sdk/issues/126, but no good.

I'm on v2.6 of the sdk.

**Comment by drum5ormore** [comment]
Nevermind.  Was able to resolve the problem in my own code.
