### ISSUE TITLE
adgroup_creation.php step 7.  Error: Invalid parameter.

### ISSUE THREAD

**Issue by binbin4649** [facebook/facebook-php-ads-sdk#260]
Hi

I have to test the [/php-ads-sdk/examples/adgroup_creation.php].

Step 1 - 6 is no problem.
Step 7 is error.

The code in question.

```
$account_id = 'act_999999999999999';
$creative_id = '9999999999999';
$adset_id = '9999999999999';

$ad = new Ad(null, $account_id);
$ad->setData(array(
  AdFields::CREATIVE =>
    array('creative_id' => $creative_id),
  AdFields::NAME => 'My First Ad',
  AdFields::ADSET_ID => $adset_id,
));
$ad->create();
echo 'Ad ID:' . $ad->id . "\n";

```

Show error.

```
Error: Invalid parameter
#0 /var/www/pr-bazooka/vendors/facebook/php-ads-sdk/src/FacebookAds/Http/Client.php(215): FacebookAds\Http\Exception\RequestException::create(Object(FacebookAds\Http\Response))
#1 /var/www/pr-bazooka/vendors/facebook/php-ads-sdk/src/FacebookAds/Http/Request.php(282): FacebookAds\Http\Client->sendRequest(Object(FacebookAds\Http\Request))
#2 /var/www/pr-bazooka/vendors/facebook/php-ads-sdk/src/FacebookAds/Api.php(151): FacebookAds\Http\Request->execute()
#3 /var/www/pr-bazooka/vendors/facebook/php-ads-sdk/src/FacebookAds/Api.php(193): FacebookAds\Api->executeRequest(Object(FacebookAds\Http\Request))
#4 /var/www/pr-bazooka/vendors/facebook/php-ads-sdk/src/FacebookAds/Object/AbstractCrudObject.php(208): FacebookAds\Api->call('/act_4727572227...', 'POST', Array)
#5 /var/www/pr-bazooka/app/Model/Facebook.php(149): FacebookAds\Object\AbstractCrudObject->create()
#6 /var/www/pr-bazooka/app/Console/Command/TestShell.php(7): Facebook->test()
#7 /var/www/pr-bazooka/lib/Cake/Console/Shell.php(440): TestShell->main()
#8 /var/www/pr-bazooka/lib/Cake/Console/ShellDispatcher.php(209): Shell->runCommand(NULL, Array)
#9 /var/www/pr-bazooka/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#10 /var/www/pr-bazooka/app/Console/cake.php(47): ShellDispatcher::run(Array)
#11 {main}
```

How is the problem? Please tell me.

**Comment by daphyFB** [comment]
Thanks for reporting SDK bugs! There is actually a bug in our Object util. We're working on a fix and will update you as soon as possible. Thanks again for reporting!

**Comment by daphyFB** [comment]
Thanks for reporting the Ads API SDK bug! We cannot repo what you have reported and need more information to investigate. Could you please let us know if:
1) Have you changed anything in the examples/adgroup_creation.php file other than the configuration section (line 26 ~ line 33)?
2) If you did change any thing other than line 26 ~ line 33, could you please share the changes you made?

Please do not share any id or secret settings.
Thanks!

**Comment by binbin4649** [comment]
reply. Thank you very much.

> 1) Have you changed anything in the examples/adgroup_creation.php file other than the configuration section (line 26 ~ line 33)?

There is no change. I think.
configuration section (line 26 ~ line 33) no change.

> Please do not share any id or secret settings.

I understood. Thank you.

Step by step the  testing.
Show the full code.

```
<?php
//App::import('Vendor', 'facebook');
$loader = include '/var/www/pr-bazooka/vendors/autoload.php';
use FacebookAds\Api;
use FacebookAds\Object\AdAccount;
use FacebookAds\Object\Fields\AdAccountFields;
use FacebookAds\Object\Campaign;
use FacebookAds\Object\Fields\CampaignFields;
use FacebookAds\Object\Values\AdObjectives;
use FacebookAds\Object\AdUser;
use FacebookAds\Object\Fields\AdUserFields;
//Step 3 Search Targeting
use FacebookAds\Object\TargetingSearch;
use FacebookAds\Object\Search\TargetingSearchTypes;
use FacebookAds\Object\TargetingSpecs;
use FacebookAds\Object\Fields\TargetingSpecsFields;
// Step 4 Create the AdSet
use FacebookAds\Object\AdSet;
use FacebookAds\Object\Fields\AdSetFields;
use FacebookAds\Object\Values\OptimizationGoals;
use FacebookAds\Object\Values\BillingEvents;
// Step 5 Create an AdImage
use FacebookAds\Object\AdImage;
use FacebookAds\Object\Fields\AdImageFields;
// Step 6 Create an AdCreative
use FacebookAds\Object\AdCreative;
use FacebookAds\Object\Fields\AdCreativeFields;
// Step 7 Create an Ad
use FacebookAds\Object\Ad;
use FacebookAds\Object\Fields\AdFields;

$access_token = '999999999999';
$app_id = '999999999999';
$app_secret = '999999999999';
Api::init($app_id, $app_secret, $access_token);

class Facebook extends AppModel {

	public $name = 'Facebook';
	public $useTable = 'facebooks';

	public function test(){
		/*
		//Step 2 Create the Campaign
		$campaign  = new Campaign(null, $account->id);
		/*
		$campaign->setData(array(
		  CampaignFields::NAME => 'My First Campaign',
		  CampaignFields::OBJECTIVE => AdObjectives::LINK_CLICKS,
		));
		$campaign->validate()->create(array(
		  Campaign::STATUS_PARAM_NAME => Campaign::STATUS_PAUSED,
		));
		echo "Campaign ID:" . $campaign->id . "\n";
		*/
		//var_dump($campaign->id);
		
		
		/*
		// Step 3 Search Targeting
		$results = TargetingSearch::search(
		$type = TargetingSearchTypes::INTEREST,
		$class = null,
		$query = 'app');
		// we'll take the top result for now
		$target = (count($results)) ? $results->current() : null;
		echo "Using target: ".$target->id." : ".$target->name."\n";
		/*
		$targeting = new TargetingSpecs();
		$targeting->{TargetingSpecsFields::GEO_LOCATIONS}
		  = array('countries' => array('JP'));
		$targeting->{TargetingSpecsFields::INTERESTS} = array(
		    array(
		        'id' => $target->id,
		        'name' => $target->name,
		    ),
		);
		
		// Step 4 Create the AdSet ,$targetingこれも必要		
		$account_id = 'act_999999999999';
		$campaign_id = '999999999999';
		$adset = new AdSet(null, $account_id);
		$adset->setData(array(
		  AdSetFields::NAME => 'My First AdSet',
		  AdSetFields::CAMPAIGN_ID => $campaign_id,
		  AdSetFields::DAILY_BUDGET => '150',
		  AdSetFields::TARGETING => $targeting,
		  AdSetFields::OPTIMIZATION_GOAL => OptimizationGoals::REACH,
		  AdSetFields::BILLING_EVENT => BillingEvents::IMPRESSIONS,
		  AdSetFields::BID_AMOUNT => 100,
		  AdSetFields::START_TIME =>
		    (new \DateTime("+1 week"))->format(\DateTime::ISO8601),
		  AdSetFields::END_TIME =>
		    (new \DateTime("+2 week"))->format(\DateTime::ISO8601),
		));
		
		$adset->validate()->create(array(
		  AdSet::STATUS_PARAM_NAME => AdSet::STATUS_ACTIVE,
		));
		
		echo 'AdSet  ID: '. $adset->id . "\n";
		*/
		
		/*
		// Step 5
		// Image Hash: 999999999999
		$account_id = 'act_999999999999';
		$img_path = '/var/www/pr-bazooka/app/webroot/files/facebook/1.jpg';		
		$image = new AdImage(null, $account_id);
		$image->{AdImageFields::FILENAME} = $img_path;
		$image->create();
		echo 'Image Hash: '.$image->hash . "\n";
		*/
		
		/*
		// Step 6
		// Creative ID: 999999999999
		$account_id = 'act_999999999999';
		$imag_hash = '999999999999';
		$creative = new AdCreative(null, $account_id);
		$creative->setData(array(
		  AdCreativeFields::NAME => 'Sample Creative',
		  AdCreativeFields::TITLE => 'Welcome to the Jungle',
		  AdCreativeFields::BODY => 'We\'ve got fun \'n\' games',
		  AdCreativeFields::IMAGE_HASH => $imag_hash,
		  AdCreativeFields::OBJECT_URL => 'http://www.example.com/',
		));		
		$creative->create();
		echo 'Creative ID: '.$creative->id . "\n";
		*/
		
		
		// Step 7
		$account_id = 'act_999999999999';
		$creative_id = '999999999999';
		$adset_id = '999999999999';
		
		$ad = new Ad(null, $account_id);
		$ad->setData(array(
		  AdFields::CREATIVE =>
		    array('creative_id' => $creative_id),
		  AdFields::NAME => 'My First Ad',
		  AdFields::ADSET_ID => $adset_id,
		));
		$ad->create();
		echo 'Ad ID:' . $ad->id . "\n";
		
		/*
		$fields = array(
		  AdFields::NAME => 'My Ad',
		  AdFields::ADSET_ID => $adset_id,
		  AdFields::STATUS => Ad::STATUS_PAUSED,
		  AdFields::CREATIVE => array(
		    'creative_id' => $creative_id,
		  ),
		);		
		$ad = new Ad(null, $account_id);
		$ad->create($fields);
		echo 'Ad ID:' . $ad->id . "\n";
		*/
	}
```

**Comment by howlittlegrass** [comment]
How about to catch the exception in "Step 7" by try...catch block, then var_dump the whole exception to see if there is more details about the error?

Just my personal recommendation :)

e.g:
```
    try {
        // Step 7
        $account_id = 'act_999999999999';
        $creative_id = '999999999999';
        $adset_id = '999999999999';

        $ad = new Ad(null, $account_id);
        $ad->setData(array(
          AdFields::CREATIVE =>
            array('creative_id' => $creative_id),
          AdFields::NAME => 'My First Ad',
          AdFields::ADSET_ID => $adset_id,
        ));
        $ad->create();
        echo 'Ad ID:' . $ad->id . "\n";
    catch (Exception $e) {
        var_dump($e);
    }
```

**Comment by avastamin** [comment]
@howlittlegrass: This is nice idea to debug. I got details about my problem and solved it.

**Comment by daphyFB** [comment]
Thanks @howlittlegrass !

**Comment by daphyFB** [comment]
Closing since there is no more work items needed.

**Comment by khemraj891289** [comment]
@daphyFB please help me how you solve this problem?
 i have tried try catch method and get error but how i solve it please help me ?

**Comment by howlittlegrass** [comment]
@khemraj891289 

what's your error message? 
I always got error details by following code, and then solved different issues according to different error message.
---------------------------------------
use FacebookAds\Exception\Exception;
use FacebookAds\Http\Exception\RequestException;
use FacebookAds\Http\Exception\AuthorizationException;

try {
	//user code here
} catch (AuthorizationException $e) {
	$err_info = json_decode($e->getResponse()->getBody(), true);
	print_r($err_info);
} catch (RequestException $e) {
	$err_info = json_decode($e->getResponse()->getBody(), true);
	print_r($err_info);
} catch (Exception $e) {
	$err_info = $e->getMessage();
	print_r($err_info);
} catch (\Exception $e) {
	$err_info = $e->getMessage();
	print_r($err_info);
}
