### ISSUE TITLE
 (#12) attribution_window_days field is deprecated for versions v2.9 and higher

### ISSUE THREAD

**Issue by rpLogicode** [facebook/facebook-php-ads-sdk#339]
I am setting only minimum required fields while create adset yet this pops up every time I try to create adset.

`#0 D:\rishiraj\htdocs\app\master\vendor\facebook\php-ads-sdk\src\FacebookAds\Http\Client.php(215): FacebookAds\Http\Exception\RequestException::create(Object(FacebookAds\Http\Response))
#1 D:\rishiraj\htdocs\app\master\vendor\facebook\php-ads-sdk\src\FacebookAds\Http\Request.php(282): FacebookAds\Http\Client->sendRequest(Object(FacebookAds\Http\Request))
#2 D:\rishiraj\htdocs\app\master\vendor\facebook\php-ads-sdk\src\FacebookAds\Api.php(163): FacebookAds\Http\Request->execute()
#3 D:\rishiraj\htdocs\app\master\vendor\facebook\php-ads-sdk\src\FacebookAds\Api.php(205): FacebookAds\Api->executeRequest(Object(FacebookAds\Http\Request))
#4 D:\rishiraj\htdocs\app\master\vendor\facebook\php-ads-sdk\src\FacebookAds\Object\AbstractCrudObject.php(252): FacebookAds\Api->call('/12033000000...', 'GET', Array)
`

**Comment by rpLogicode** [comment]
Sorry , it was an error in my side where I was reading the wrong field attribution_window_days, should've been obvious, sorry for trouble
