### ISSUE TITLE
Uncaught exception 'FacebookAds\Http\Exception\ServerException'

### ISSUE THREAD

**Issue by sachinsinghshekhawat** [facebook/facebook-php-ads-sdk#382]
PHP SDK version : 2.10.*
I have a script which pulls campaign insights and most of the time scripts works perfectly but sometime it fails with throwing exception:

PHP Fatal error:  Uncaught exception 'FacebookAds\Http\Exception\ServerException' with message 'An unknown error occurred' in /var/app/current/vendor/facebook/php-ads-sdk/src/FacebookAds/Http/Exception/RequestException.php:147
Stack trace:
#0 /var/app/current/vendor/facebook/php-ads-sdk/src/FacebookAds/Http/Client.php(215): FacebookAds\Http\Exception\RequestException::create(Object(FacebookAds\Http\Response))
#1 /var/app/current/vendor/facebook/php-ads-sdk/src/FacebookAds/Http/Request.php(282): FacebookAds\Http\Client->sendRequest(Object(FacebookAds\Http\Request))
#2 /var/app/current/vendor/facebook/php-ads-sdk/src/FacebookAds/Api.php(162): FacebookAds\Http\Request->execute()
#3 /var/app/current/vendor/facebook/php-ads-sdk/src/FacebookAds/Api.php(204): FacebookAds\Api->executeRequest(Object(FacebookAds\Http\Request))
#4 /var/app/current/vendor/facebook/php-ads-sdk/src/FacebookAds/ApiRequest.php(183): FacebookAds\Api->call('/*******account - id ******/...', 'GET', Array, Array)
#5 /var/app/current/vendor/facebook/php-ads-sdk/src/FacebookAds in /var/app/current/vendor/facebook/php-ads-sdk/src/FacebookAds/Http/Exception/RequestException.php on line 147

**Comment by mmccaff** [comment]
I've been getting the same exception intermittently when pulling insights from campaigns. It has just started over the last month or two, and never happened for at least a year before that.

Did you ever find a resolution to this @sachinsinghshekhawat ?

**Comment by sachinsinghshekhawat** [comment]
not any resolution, but i have added a sleep function in b/w API calls, assuming API call limit is throwing the exception. Its working for me now.

**Comment by mmccaff** [comment]
Interesting. I am only making one call to getInsights and no other calls around the time that I am doing that, however I am using implicit fetching to iterate through the results, which behind the scenes is potentially making multiple calls. eg.

```
$insightsCursor = $account->getInsights([], $params);

// Turn on implicit fetching; automatically fetches more at page end while iterating (foreach, Cursor::next, Cursor::prev) instead of $cursor->fetchAfter();
$insightsCursor->setUseImplicitFetch(true);

foreach ($insightsCursor as $insight) {
  $clicks = $insight->{AdsInsightsFields::INLINE_LINK_CLICKS};
  $spend = $insight->{AdsInsightsFields::SPEND};
  $adsetName = $insight->{AdsInsightsFields::ADSET_NAME};

  $exploded = explode('_', $adsetName);
  $utmSource = array_shift($exploded);

  $normalizedResults[] = (object)['clicks' => $clicks, 'spend' => $spend, 'utmSource' => $utmSource, 'name' => $adsetName];
}
```

Before I go off experimenting, I am curious, do you use implicit fetching and did you find that you needed to sleep within each loop iteration? If so, how much of a sleep did you end up adding?

**Comment by sachinsinghshekhawat** [comment]
In my case , i was running getAdSets for each campaign in a loop So it was clear that i was making an API call, i added 2 sec after each call.

**Comment by sachinsinghshekhawat** [comment]
worked for you?

**Comment by mmccaff** [comment]
I haven't tried yet, but I'll report back if I make any changes that help.  I think the first thing that I'll do is retry a few times on catching an exception.

**Comment by steenMSU** [comment]
Hi there, gents! I'm new to the FB api and am currently running into the same exception error when looping through multiple accounts for ad insights. I was curious as to if there was a solution or work around determined? I have attempted to use the sleep function in my loop, but I seem to get that pesky error here and there. Please let me know what you've discovered since this post. Thanks!

**Comment by mmccaff** [comment]
I ended up retrying up to 3x on catching an exception (and sleeping 1s before a retry). That "solved" the problem for me.

This was on a daily job that was failing to complete once every few days, now I have gone about three weeks without it failing to complete.

Not ideal, but it seems like the only way to workaround what seems like a problem on Facebook's side.

**Comment by steenMSU** [comment]
Great! This seems to work. Similar to you, 3 seems to be the magic # of attempts/loops it takes to correct each bad query. I suppose I'm still pretty uncomfortable not knowing the cause of the error(s) though. Anyways, thank you for pointing me in the right direction! Take care!

**Comment by sachinsinghshekhawat** [comment]
Great! 
Same here, i am also trying to figure out the actual issue. Lets keep this open and wait for anyone from facebook.

**Comment by steenMSU** [comment]
FWIW, this error is definitely not exclusive to ad insights. I’m experiencing this with Account Activity as well. Although it does appear to be an API issue, I’m not certain it’s explicitly related to call frequency. In my LIMITED experience, ad accounts with higher activity (by way of more adsets/ads) tend to produce the error more frequently. That said, correlation !== causation.
